import type { Coupon } from '@/types/coupon'

const now = Date.now()
const day = 86400000

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'cp_1',
    title: '美团满30减8',
    description: '餐饮类 · 官方联盟',
    category: '餐饮',
    emoji: '🍜',
    amount: 8,
    minSpend: 30,
    status: 'available',
    expireAt: now + day * 7,
    link: 'https://i.meituan.com',
    linkType: 'webview',
  },
  {
    id: 'cp_2',
    title: '京东满99减15',
    description: '购物类 · 官方联盟',
    category: '购物',
    emoji: '🛒',
    amount: 15,
    minSpend: 99,
    status: 'available',
    expireAt: now + day * 14,
    link: 'https://m.jd.com',
    linkType: 'webview',
  },
  {
    id: 'cp_3',
    title: '出行立减5元',
    description: '打车类 · 官方联盟',
    category: '出行',
    emoji: '🚕',
    amount: 5,
    minSpend: 15,
    status: 'available',
    expireAt: now + day * 3,
    link: 'https://www.didiglobal.com',
    linkType: 'webview',
  },
  {
    id: 'cp_4',
    title: '超市满50减10',
    description: '已使用',
    category: '购物',
    emoji: '🏪',
    amount: 10,
    minSpend: 50,
    status: 'used',
    expireAt: now + day * 30,
    link: 'https://www.walmart.cn',
    linkType: 'webview',
  },
  {
    id: 'cp_5',
    title: '新人专享券',
    description: '已过期',
    category: '餐饮',
    emoji: '🎁',
    amount: 20,
    minSpend: 0,
    status: 'expired',
    expireAt: now - day,
    link: 'https://i.meituan.com',
    linkType: 'webview',
  },
]
